development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: pomtv_dev_db
  pool: 5
  username: root
  password: 
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: pomtv_test_db
  pool: 5
  username: pomtv_test_db
  password: pomtv_test_db
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: pomtv_prod_db
  pool: 5
  username: pomtv_prod_db
  password: pomtv_prod_db
  host: localhost
