require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InstallBooksController do

  # This should return the minimal set of attributes required to create a valid
  # InstallBook. As you add validations to InstallBook, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all install_books as @install_books" do
      install_book = InstallBook.create! valid_attributes
      get :index
      assigns(:install_books).should eq([install_book])
    end
  end

  describe "GET show" do
    it "assigns the requested install_book as @install_book" do
      install_book = InstallBook.create! valid_attributes
      get :show, :id => install_book.id.to_s
      assigns(:install_book).should eq(install_book)
    end
  end

  describe "GET new" do
    it "assigns a new install_book as @install_book" do
      get :new
      assigns(:install_book).should be_a_new(InstallBook)
    end
  end

  describe "GET edit" do
    it "assigns the requested install_book as @install_book" do
      install_book = InstallBook.create! valid_attributes
      get :edit, :id => install_book.id.to_s
      assigns(:install_book).should eq(install_book)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InstallBook" do
        expect {
          post :create, :install_book => valid_attributes
        }.to change(InstallBook, :count).by(1)
      end

      it "assigns a newly created install_book as @install_book" do
        post :create, :install_book => valid_attributes
        assigns(:install_book).should be_a(InstallBook)
        assigns(:install_book).should be_persisted
      end

      it "redirects to the created install_book" do
        post :create, :install_book => valid_attributes
        response.should redirect_to(InstallBook.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved install_book as @install_book" do
        # Trigger the behavior that occurs when invalid params are submitted
        InstallBook.any_instance.stub(:save).and_return(false)
        post :create, :install_book => {}
        assigns(:install_book).should be_a_new(InstallBook)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InstallBook.any_instance.stub(:save).and_return(false)
        post :create, :install_book => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested install_book" do
        install_book = InstallBook.create! valid_attributes
        # Assuming there are no other install_books in the database, this
        # specifies that the InstallBook created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InstallBook.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => install_book.id, :install_book => {'these' => 'params'}
      end

      it "assigns the requested install_book as @install_book" do
        install_book = InstallBook.create! valid_attributes
        put :update, :id => install_book.id, :install_book => valid_attributes
        assigns(:install_book).should eq(install_book)
      end

      it "redirects to the install_book" do
        install_book = InstallBook.create! valid_attributes
        put :update, :id => install_book.id, :install_book => valid_attributes
        response.should redirect_to(install_book)
      end
    end

    describe "with invalid params" do
      it "assigns the install_book as @install_book" do
        install_book = InstallBook.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InstallBook.any_instance.stub(:save).and_return(false)
        put :update, :id => install_book.id.to_s, :install_book => {}
        assigns(:install_book).should eq(install_book)
      end

      it "re-renders the 'edit' template" do
        install_book = InstallBook.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InstallBook.any_instance.stub(:save).and_return(false)
        put :update, :id => install_book.id.to_s, :install_book => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested install_book" do
      install_book = InstallBook.create! valid_attributes
      expect {
        delete :destroy, :id => install_book.id.to_s
      }.to change(InstallBook, :count).by(-1)
    end

    it "redirects to the install_books list" do
      install_book = InstallBook.create! valid_attributes
      delete :destroy, :id => install_book.id.to_s
      response.should redirect_to(install_books_url)
    end
  end

end
